"""add is_admin to users

Revision ID: d5c8417cce11
Revises: e9bacc4c078b
Create Date: 2026-09-21 14:14:46.124809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c8417cce11'
down_revision: Union[str, Sequence[str], None] = 'e9bacc4c078b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
    'users',
    sa.Column(
        'is_admin',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
